name: Gerar animação de cobra

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gerar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar arquivo de contribuição animado
        uses: Platane/snk@v3
        with:
          github_user_name: monike44
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push da animação
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizar animação da cobra"
          add: "dist/github-contribution-grid-snake.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
